"""Add roles table and role_policies association

Revision ID: 28e9652f0372
Revises: a1b2c3d4e5f6
Create Date: 2025-12-27 08:47:20.753352

"""

import sqlalchemy as sa
from alembic import op

from app.models.types import GUID

# revision identifiers, used by Alembic.
revision = "28e9652f0372"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create roles table
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("company_id", GUID(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "company_id", name="uq_role_name_company"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_roles_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            "ix_roles_company_active",
            ["company_id", "is_active"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_roles_name"), ["name"], unique=False)

    # Create role_policies association table
    op.create_table(
        "role_policies",
        sa.Column("role_id", GUID(), nullable=False),
        sa.Column("policy_id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "policy_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_policies")

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_name"))
        batch_op.drop_index("ix_roles_company_active")
        batch_op.drop_index(batch_op.f("ix_roles_company_id"))

    op.drop_table("roles")
    # ### end Alembic commands ###
