"""initial migration

Revision ID: 8365b8792dc0
Revises: 47df9b3cded2
Create Date: 2025-12-21 22:11:05.641863

"""

import sqlalchemy as sa
from alembic import op

from app.models.types import GUID, JSONB

# revision identifiers, used by Alembic.
revision = "8365b8792dc0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("extra_metadata", JSONB(), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy")
    # ### end Alembic commands ###
