"""add permissions table

Revision ID: 9600ef699017
Revises: 8365b8792dc0
Create Date: 2025-12-27 07:01:47.629872

"""

import sqlalchemy as sa
from alembic import op

from app.models.types import GUID

# revision identifiers, used by Alembic.
revision = "9600ef699017"
down_revision = "8365b8792dc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("resource_name", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permissions_name"), ["name"], unique=True)
        batch_op.create_index(
            "ix_permissions_service_resource",
            ["service", "resource_name"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index("ix_permissions_service_resource")
        batch_op.drop_index(batch_op.f("ix_permissions_name"))

    op.drop_table("permissions")
    # ### end Alembic commands ###
