"""add policies and policy_permissions tables

Revision ID: a1b2c3d4e5f6
Revises: 9600ef699017
Create Date: 2025-12-27 08:25:00.000000

"""

import sqlalchemy as sa
from alembic import op

from app.models.types import GUID

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "9600ef699017"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create policies table
    op.create_table(
        "policies",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("company_id", GUID(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="1"),
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "company_id", name="uq_policy_name_company"),
    )
    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_policies_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            "ix_policies_company_active",
            ["company_id", "is_active"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_policies_name"), ["name"], unique=False)

    # Create policy_permissions association table
    op.create_table(
        "policy_permissions",
        sa.Column("policy_id", GUID(), nullable=False),
        sa.Column("permission_id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policies.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("policy_id", "permission_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("policy_permissions")

    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policies_name"))
        batch_op.drop_index("ix_policies_company_active")
        batch_op.drop_index(batch_op.f("ix_policies_company_id"))

    op.drop_table("policies")
    # ### end Alembic commands ###
