"""Add user_roles table and associations

Revision ID: d255df3d9647
Revises: 28e9652f0372
Create Date: 2025-12-27 09:12:54.240138

"""

import sqlalchemy as sa
from alembic import op

from app.models.types import GUID

# revision identifiers, used by Alembic.
revision = "d255df3d9647"
down_revision = "28e9652f0372"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("role_id", GUID(), nullable=False),
        sa.Column("company_id", GUID(), nullable=False),
        sa.Column("project_id", GUID(), nullable=True),
        sa.Column(
            "scope_type", sa.String(length=20), server_default="direct", nullable=False
        ),
        sa.Column("granted_by", GUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_roles_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index("ix_user_roles_expires_at", ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_roles_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_user_roles_role_company", ["role_id", "company_id"], unique=False
        )
        batch_op.create_index(
            "ix_user_roles_unique_active",
            ["user_id", "role_id", "company_id", "project_id", "is_active"],
            unique=True,
            postgresql_where=sa.text("is_active = true"),
        )
        batch_op.create_index(
            "ix_user_roles_user_company", ["user_id", "company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_roles_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.alter_column(
            "company_id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.Uuid(),
            existing_nullable=False,
        )

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "company_id",
            existing_type=sa.VARCHAR(length=36),
            type_=sa.Uuid(),
            existing_nullable=False,
        )
        batch_op.drop_column("priority")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "priority", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False
            )
        )
        batch_op.alter_column(
            "company_id",
            existing_type=sa.Uuid(),
            type_=sa.VARCHAR(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.alter_column(
            "company_id",
            existing_type=sa.Uuid(),
            type_=sa.VARCHAR(length=36),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_roles_user_id"))
        batch_op.drop_index("ix_user_roles_user_company")
        batch_op.drop_index(
            "ix_user_roles_unique_active", postgresql_where=sa.text("is_active = true")
        )
        batch_op.drop_index("ix_user_roles_role_company")
        batch_op.drop_index(batch_op.f("ix_user_roles_project_id"))
        batch_op.drop_index("ix_user_roles_expires_at")
        batch_op.drop_index(batch_op.f("ix_user_roles_company_id"))

    op.drop_table("user_roles")
    # ### end Alembic commands ###
